name: Update Issue Count

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update_issue_count:
    permissions:
      contents: write
      issues: read 
    runs-on: ubuntu-latest

    env:
      REPO: "sailaja-adapa/Shresta"  # Set the repository name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      
      # Fetch Open Issues Count
      - name: Get Open Issues Count
        run: |
          OPEN_ISSUE_COUNT=$(gh issue list --repo $REPO --state open --json number --jq 'length')
          echo "OPEN_ISSUE_COUNT=$OPEN_ISSUE_COUNT" >> $GITHUB_ENV
          echo "Open Issues: $OPEN_ISSUE_COUNT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Fetch Closed Issues Count
      - name: Get Closed Issues Count
        run: |
          CLOSED_ISSUE_COUNT=$(gh issue list --repo $REPO --state closed --json number --jq 'length')
          echo "CLOSED_ISSUE_COUNT=$CLOSED_ISSUE_COUNT" >> $GITHUB_ENV
          echo "Closed Issues: $CLOSED_ISSUE_COUNT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Calculate Total Issues (Fixed)
      - name: Calculate Total Issues
        run: |
          TOTAL_ISSUE_COUNT=$((OPEN_ISSUE_COUNT + CLOSED_ISSUE_COUNT))
          echo "TOTAL_ISSUE_COUNT=$TOTAL_ISSUE_COUNT" >> $GITHUB_ENV
          echo "Final Total Issues: $TOTAL_ISSUE_COUNT"

      # Remove Old JSON File Before Writing (Fix)
      - name: Remove Old JSON File
        run: rm -f issue-count.json

      # Create Updated JSON File
      - name: Create JSON File
        run: |
          echo '{ "schemaVersion": 1, "label": "Total Issues", "message": "'"$TOTAL_ISSUE_COUNT"'", "color": "red" }' > issue-count.json
          echo "Updated issue-count.json:"
          cat issue-count.json

      # Check for Changes Before Committing (Fix)
      - name: Check for Changes
        run: |
          git status
          git diff issue-count.json || echo "No changes detected"

      # Reset Unstaged Changes & Pull Latest Code (Fix)
      - name: Reset and Pull Latest Changes
        run: |
          git reset --hard HEAD  # Discards any unstaged changes
          git clean -fd  # Removes untracked files
          git pull --rebase origin main || echo "No changes to pull"

      # Commit and Push Changes (Fix)
      - name: Commit and Push Changes
        run: |
          if git diff --quiet issue-count.json; then
            echo "No changes to commit"
          else
            git add -f issue-count.json
            git commit -m "Update issue count to $TOTAL_ISSUE_COUNT"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debug Steps for Verification
      - name: Debug JSON File
        run: cat issue-count.json

      - name: Debug Variables
        run: |
          echo "OPEN_ISSUE_COUNT: $OPEN_ISSUE_COUNT"
          echo "CLOSED_ISSUE_COUNT: $CLOSED_ISSUE_COUNT"
          echo "TOTAL_ISSUE_COUNT: $TOTAL_ISSUE_COUNT"

      - name: Debug Repository Name
        run: echo "Using Repository: $REPO"

      - name: Verify Issue Count Calculation (Fix)
        run: |
          echo "Rechecking total issues: $(( $(gh issue list --repo $REPO --state open --json number --jq 'length') + $(gh issue list --repo $REPO --state closed --json number --jq 'length') ))"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
